version: '3.8'

services:
  web:
    image: ksamnole/assessor
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev